CREATE TABLE IF NOT EXISTS project
(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    project_name VARCHAR(100) NOT NULL,
    description  TEXT,
    create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    create_by    VARCHAR(50),
    update_by    VARCHAR(50)
);

